# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS POSTGRESQL
# ==========================================

# Credenciales y URL de tu base de datos local
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/academic_db

# ==========================================
# CONFIGURACIÓN DE HIBERNATE (MAGIA ORM)
# ==========================================

# Esta línea es CLAVE en desarrollo.
# "drop-and-create" le dice a Hibernate: "Cada vez que yo inicie el servidor,
# borra todas las tablas y vuélvelas a crear leyendo mis clases de Java".
# (OJO: ¡Jamás usar esto en producción porque borra todos los datos!)
quarkus.hibernate-orm.database.generation=drop-and-create

# Opcional pero muy útil: Imprime en la consola el SQL que Hibernate genera por detrás
quarkus.hibernate-orm.log.sql=true